# Generated by Django 3.0.7 on 2020-08-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='stauts',
            new_name='status',
        ),
    ]
