# Generated by Django 3.0.7 on 2020-08-05 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        ('account', '0004_auto_20200805_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(through='account.UserInterest', to='photo.HashTag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.HashTag'),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
