# Generated by Django 3.0.7 on 2020-08-06 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200806_0958'),
        ('account', '0005_auto_20200806_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(related_name='like_photo', through='account.Like', to='photo.Photo'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_user', to='account.User'),
        ),
    ]
