# Generated by Django 3.0.7 on 2020-08-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200806_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
