# Generated by Django 3.0.7 on 2020-08-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
