# Generated by Django 3.0.7 on 2020-08-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200806_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
