# Generated by Django 3.0.7 on 2020-08-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
    ]
